version: '3'
services:

  jms:
    container_name: jms
    image: vromero/activemq-artemis
    restart: always
    environment:
      ARTEMIS_USERNAME: 'luizcasagrande'
      ARTEMIS_PASSWORD: 'password'
    ports:
      - 61616:61616
      - 8161:8161
    expose:
      - 61616
      - 8161
